name: flutter_chat_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  http: ^1.2.1 # Add this line
  stomp_dart_client: ^1.0.1
  intl: ^0.20.2 # Add this line
  provider: ^6.1.2
  flutter_native_splash: ^2.4.6
  # ✅ Add this package for secure data persistence
  flutter_secure_storage: ^9.2.4
  # ✅ Add these packages for image picking and Firebase
  image_picker: ^1.1.2
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_milinillion.png

# Add this entire block at the end of the file
flutter_native_splash:
  # The background color for your splash screen.
  color: "#121212" # The same dark color as our Milinillion screen

  # (Optional) If you have an image logo, you can specify it here.--------------- this is important to replace the flutter logo on splash screen
  # For now, we will just use the background color for a clean look.
  # image: assets/logo.png 

  # Android 12 introduced a new splash screen design. This section is for that.
  android_12:
    color: "#121212"
    # image: assets/logo.png

